### ISSUE TITLE
Error: listen EADDRNOTAVAIL: address not available

### ISSUE THREAD

**Issue by sinewave** [naimo84/node-red-contrib-fakeroku#3]
Was really excited to discover this node however I keep running into this error when trying to configure it.

I'm running Node-RED in a docker using Unraid which has an IP of 192.168.1.217. The docker is setup using bridge mode if that matters.

Here's the error I'm getting. I've also tried using 127.0.0.1 or localhost as the IP as well as many different ports with no luck.

<img width="1755" alt="fakeroku error" src="https://user-images.githubusercontent.com/84384/82288549-93da8e80-9957-11ea-9243-4fb557dc2aa5.png">

**Comment by naimo84** [comment]
Hi,
recently I had the Same problem, while I was switching to proxmox. This time only 0.0.0.0 worked for me, so the server is listening on all interfaces. May you please try this one?

Regards, 
Benjamin
