### ISSUE TITLE
Running inside Docker: which network ports to expose?

### ISSUE THREAD

**Issue by ThinkPadNL** [naimo84/node-red-contrib-fakeroku#6]
Hi,

I am running Node-RED in a Docker container. Are there certain ports that i need to expose to the outside of the container?
Currently i cannot find the Roku device.

My Harmony Hub & Docker are in separate VLANs, but firewall wise i have installed a mDNS reflector and opened up the network from both these device to each other. I am now thinking that maybe in the Docker container i need to open certain ports, but which one???

**Comment by ThinkPadNL** [comment]
Okay, i read some more and it seems that receiving multicast traffic inside a Docker container is quite hard!?
I tried changing my Node-RED container from network `bridge` to `host` but it still cannot be found by the Harmony Hub.

Is there anyone who has this working inside a Docker container?

**Comment by naimo84** [comment]
Hi @ThinkPadNL,

unfortunatelly I'm not running node-RED for my harmony as a DockerContainer. It tried it, but as you write it was not possible for me to get it working :/
sry, that I can't give you any advice...

greetings,
Benjamin

**Comment by naimo84** [comment]
Hi @ThinkPadNL,

a bit late, but have you tried this? https://stackoverflow.com/questions/37214608/docker-receiving-multicast-traffic
I did some researching again, but I didn't get this working... Would like to have fakreroku inside docker myself...
Otherwise I would close this using, because we can't do anything for this :(

Greets,
Benjamin

**Comment by ThinkPadNL** [comment]
I don't have any usecase for fakeroku anymore, so am not using it. I leave this for someone else to test.
Will close the issue.

**Comment by bokaklav** [comment]
Hi @naimo84 I am currently using fakeroku on a vm to allow Harmony to connect to a new TV it doesn't support.   Its working beautifully, but I would rather have all this in one docker container.  I cannot seem to get the network discovery to work in  my docker compose/Dockerfiile file.   Any luck with this?
